import React from 'react';

export const PrivacyPolicyPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-ehyo-bg pt-28 pb-24">
      <div className="container mx-auto px-6 max-w-3xl">
        <h1 className="font-serif text-4xl md:text-5xl font-bold mb-3 text-ehyo-text">Privacy Policy</h1>
        <p className="text-stone-400 text-sm mb-12">Last updated: July 31, 2025</p>

        <p className="text-stone-600 leading-relaxed mb-10">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <Section title="Interpretation and Definitions">
          <SubSection title="Interpretation">
            <p className="text-stone-600 leading-relaxed">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
          </SubSection>
          <SubSection title="Definitions">
            <p className="text-stone-600 leading-relaxed mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="space-y-3 text-stone-600 leading-relaxed">
              <DefItem term="Account" def="means a unique account created for You to access our Service or parts of our Service." />
              <DefItem term="Affiliate" def='means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.' />
              <DefItem term="Application" def="refers to EhYo, the software program provided by the Company." />
              <DefItem term="Company" def='(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to EhYo.' />
              <DefItem term="Country" def="refers to: Taiwan" />
              <DefItem term="Device" def="means any device that can access the Service such as a computer, a cellphone or a digital tablet." />
              <DefItem term="Personal Data" def="is any information that relates to an identified or identifiable individual." />
              <DefItem term="Service" def="refers to the Application." />
              <DefItem term="Service Provider" def="means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used." />
              <DefItem term="Usage Data" def="refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." />
              <DefItem term="You" def="means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." />
            </ul>
          </SubSection>
        </Section>

        <Section title="Collecting and Using Your Personal Data">
          <SubSection title="Types of Data Collected">
            <h4 className="font-semibold text-ehyo-text mb-2">Personal Data</h4>
            <p className="text-stone-600 leading-relaxed mb-3">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc list-inside text-stone-600 space-y-1 mb-6">
              <li>Email address</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="font-semibold text-ehyo-text mb-2">Usage Data</h4>
            <p className="text-stone-600 leading-relaxed mb-3">
              Usage Data is collected automatically when using the Service.
            </p>
            <p className="text-stone-600 leading-relaxed mb-3">
              Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="text-stone-600 leading-relaxed mb-3">
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>
            <p className="text-stone-600 leading-relaxed">
              We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
            </p>
          </SubSection>

          <SubSection title="Use of Your Personal Data">
            <p className="text-stone-600 leading-relaxed mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="space-y-3 text-stone-600 leading-relaxed mb-6">
              <DefItem term="To provide and maintain our Service" def=", including to monitor the usage of our Service." />
              <DefItem term="To manage Your Account:" def=" to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user." />
              <DefItem term="For the performance of a contract:" def=" the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service." />
              <DefItem term="To contact You:" def=" To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation." />
              <DefItem term="To provide You" def=" with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information." />
              <DefItem term="To manage Your requests:" def=" To attend and manage Your requests to Us." />
              <DefItem term="For business transfers:" def=" We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred." />
              <DefItem term="For other purposes" def=": We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience." />
            </ul>
            <p className="text-stone-600 leading-relaxed mb-4">We may share Your personal information in the following situations:</p>
            <ul className="space-y-3 text-stone-600 leading-relaxed">
              <DefItem term="With Service Providers:" def=" We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You." />
              <DefItem term="For business transfers:" def=" We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company." />
              <DefItem term="With Affiliates:" def=" We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us." />
              <DefItem term="With business partners:" def=" We may share Your information with Our business partners to offer You certain products, services or promotions." />
              <DefItem term="With other users:" def=" when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside." />
              <DefItem term="With Your consent" def=": We may disclose Your personal information for any other purpose with Your consent." />
            </ul>
          </SubSection>
        </Section>

        <Section title="Retention of Your Personal Data">
          <p className="text-stone-600 leading-relaxed mb-4">
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          </p>
          <p className="text-stone-600 leading-relaxed">
            The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
          </p>
        </Section>

        <Section title="Transfer of Your Personal Data">
          <p className="text-stone-600 leading-relaxed mb-4">
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
          </p>
          <p className="text-stone-600 leading-relaxed">
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
          </p>
        </Section>

        <Section title="Delete Your Personal Data">
          <p className="text-stone-600 leading-relaxed mb-4">
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            Our Service may give You the ability to delete certain information about You from within the Service.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
          </p>
          <p className="text-stone-600 leading-relaxed">
            Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
          </p>
        </Section>

        <Section title="Disclosure of Your Personal Data">
          <SubSection title="Business Transactions">
            <p className="text-stone-600 leading-relaxed">
              If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
            </p>
          </SubSection>
          <SubSection title="Law enforcement">
            <p className="text-stone-600 leading-relaxed">
              Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
            </p>
          </SubSection>
          <SubSection title="Other legal requirements">
            <p className="text-stone-600 leading-relaxed mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul className="list-disc list-inside text-stone-600 space-y-1">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>
          </SubSection>
        </Section>

        <Section title="Security of Your Personal Data">
          <p className="text-stone-600 leading-relaxed">
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>
        </Section>

        <Section title="Children's Privacy">
          <p className="text-stone-600 leading-relaxed mb-4">
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </p>
          <p className="text-stone-600 leading-relaxed">
            If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
          </p>
        </Section>

        <Section title="Links to Other Websites">
          <p className="text-stone-600 leading-relaxed mb-4">
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>
          <p className="text-stone-600 leading-relaxed">
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>
        </Section>

        <Section title="Changes to this Privacy Policy">
          <p className="text-stone-600 leading-relaxed mb-4">
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="text-stone-600 leading-relaxed mb-4">
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
          </p>
          <p className="text-stone-600 leading-relaxed">
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </p>
        </Section>

        <Section title="Contact Us">
          <p className="text-stone-600 leading-relaxed mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="space-y-2 text-stone-600">
            <li>By email: <a href="mailto:valzin@ehyo.app" className="text-ehyo-indigo hover:underline">valzin@ehyo.app</a></li>
            <li>By visiting this page on our Discord: <a href="https://discord.gg/htVu7kyx3m" target="_blank" rel="noopener noreferrer" className="text-ehyo-indigo hover:underline">https://discord.gg/htVu7kyx3m</a></li>
          </ul>
        </Section>
      </div>
    </div>
  );
};

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div className="mb-12">
    <h2 className="font-serif text-2xl font-bold text-ehyo-text mb-5 pb-3 border-b border-stone-200">{title}</h2>
    <div className="space-y-6">{children}</div>
  </div>
);

const SubSection = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div>
    <h3 className="font-semibold text-lg text-ehyo-text mb-3">{title}</h3>
    {children}
  </div>
);

const DefItem = ({ term, def }: { term: string; def: string }) => (
  <li className="flex gap-2">
    <span className="w-1.5 h-1.5 rounded-full bg-ehyo-indigo flex-shrink-0 mt-2" />
    <span><strong className="text-ehyo-text">{term}</strong>{def}</span>
  </li>
);
